### ISSUE TITLE
help compiling  

### ISSUE THREAD

**Issue by Enchantedbooz** [BoloVEVO/Kade-Engine#50]
"C:/haxelib/extension-webm/git/ndll/Windows64/extension-webm.ndll

**Comment by BoloVEVO** [comment]
if you have extension-webm already installed, run this command `lime rebuild extension-webm`

**Comment by moxie-coder** [comment]
> "C:/haxelib/extension-webm/git/ndll/Windows64/extension-webm.ndll

apparently idiots like you don’t know when to just follow instructions

**Comment by thegamenig** [comment]
WHAT i did follow the instructions

**Comment by moxie-coder** [comment]
> WHAT i did follow the instructions

apparently not from how many damn issues you make, and also I feel this just shows why we're doomed as a species

**Comment by thegamenig** [comment]
UGH!!! FINE!!!! I'm going to the instructions AGAIN!!!!

**Comment by thegamenig** [comment]
UGH FIND!!! i follow the instructions AGAIN!!!
