### ISSUE TITLE
Bug Report: when i try to build it this happens

### ISSUE THREAD

**Issue by KittenfanVR** [BoloVEVO/Kade-Engine#52]
source/PlayState.hx:121: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/DialogueBox.hx:39: characters 12-20 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/Stage.hx:867: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/LuaClass.hx:41: characters 46-58 : Type not found : StatePointer
source/Debug.hx:22: lines 22-347 : ... Defined in this class
source/LuaClass.hx:2160: characters 37-49 : Type not found : StatePointer
source/Debug.hx:22: lines 22-347 : ... Defined in this class
source/ModCore.hx:113: characters 48-71 : Type not found : polymod.FrameworkParams
source/Main.hx:22: lines 22-174 : ... Defined in this class
source/LuaClass.hx:1903: characters 37-49 : Type not found : StatePointer
source/Main.hx:22: lines 22-174 : ... Defined in this class
source/LuaClass.hx:1552: characters 37-49 : Type not found : StatePointer
source/Main.hx:22: lines 22-174 : ... Defined in this class
source/LuaClass.hx:1207: characters 38-50 : Type not found : StatePointer
source/Main.hx:22: lines 22-174 : ... Defined in this class
source/LuaClass.hx:844: characters 37-49 : Type not found : StatePointer
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/FlxGame.hx:42: lines 42-898 : ... Defined in this class
source/LuaClass.hx:443: characters 37-49 : Type not found : StatePointer
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/FlxGame.hx:42: lines 42-898 : ... Defined in this class
source/flixel/FlxCamera.hx:1072: characters 31-42 : Class<flixel.FlxG> has no field initialZoom
source/Main.hx:113: characters 59-63 : Float should be Int
source/Main.hx:113: characters 59-63 : ... For optional function argument 'updateFramerate'
source/FreeplayState.hx:64: characters 11-19 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/ChartingState.hx:120: characters 13-21 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/ChartingState.hx:1552: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:34: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:93: characters 21-29 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/VideoState.hx:25: characters 22-30 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/Stage.hx:142: characters 24-32 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/ChartingState.hx:1950: characters 33-41 : openfl.media.SoundChannel has no field __source
source/ChartingState.hx:1962: characters 25-33 : openfl.media.SoundChannel has no field __source
source/FreeplayState.hx:576: characters 31-39 : openfl.media.SoundChannel has no field __source
source/DialogueBox.hx:48: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/DialogueBox.hx:53: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/LuaClass.hx:1759: characters 3-10 : LuaClass does not have a constructor
source/LuaClass.hx:1760: characters 3-12 : Unknown identifier : className
source/LuaClass.hx:1770: characters 13-27 : Unknown identifier : SetNumProperty
source/ModchartState.hx:393: characters 37-45 : LuaSprite has no field Register
source/ModchartState.hx:549: characters 38-47 : LuaNote has no field className
source/PlayState.hx:4944: characters 14-29 : Static access to instance field SKIP_STEP_LIMIT is not allowed
source/LuaClass.hx:569: characters 3-10 : LuaClass does not have a constructor
source/LuaClass.hx:582: characters 3-12 : Unknown identifier : className
source/LuaClass.hx:592: characters 13-27 : Unknown identifier : SetNumProperty
source/ModchartState.hx:672: characters 45-53 : LuaReceptor has no field Register
source/ModchartState.hx:675: characters 3-16 : LuaGame does not have a constructor
source/LuaClass.hx:2073: characters 3-10 : LuaClass does not have a constructor
source/LuaClass.hx:2074: characters 3-12 : Unknown identifier : className
source/LuaClass.hx:2064: characters 9-14 : Class<llua.LuaL> has no field error
source/LuaClass.hx:2121: characters 10-23 : Class<llua.Lua> has no field pushcfunction (Suggestions: iscfunction, _iscfunction)
source/LuaClass.hx:2121: characters 27-36 : Unknown identifier : tweenPosC
source/LuaClass.hx:2126: characters 11-16 : Class<llua.LuaL> has no field error
source/LuaClass.hx:2140: characters 11-16 : Class<llua.LuaL> has no field error
source/LuaClass.hx:2153: characters 11-16 : Class<llua.LuaL> has no field error
source/ModchartState.hx:677: characters 19-27 : LuaWindow has no field Register
source/PlayState.hx:2144: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2146: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2154: characters 27-35 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/LuaClass.hx:1053: characters 3-10 : LuaClass does not have a constructor
source/LuaClass.hx:1056: characters 3-12 : Unknown identifier : className
source/LuaClass.hx:1200: characters 9-14 : Class<llua.LuaL> has no field error
source/LuaClass.hx:1110: characters 19-28 : Unknown identifier : className
source/PlayState.hx:1102: characters 42-50 : LuaCamera has no field Register
source/PlayState.hx:1103: characters 36-44 : LuaCamera has no field Register
source/PlayState.hx:1104: characters 38-46 : LuaCamera has no field Register
source/PlayState.hx:1105: characters 42-50 : LuaCamera has no field Register
source/PlayState.hx:1106: characters 40-48 : LuaCamera has no field Register
source/PlayState.hx:1107: characters 46-54 : LuaCamera has no field Register
source/LuaClass.hx:1390: characters 3-10 : LuaClass does not have a constructor
source/LuaClass.hx:1391: characters 3-12 : Unknown identifier : className
source/LuaClass.hx:1405: characters 13-27 : Unknown identifier : SetNumProperty
source/PlayState.hx:1108: characters 33-41 : LuaCharacter has no field Register
source/PlayState.hx:1109: characters 31-39 : LuaCharacter has no field Register
source/PlayState.hx:1110: characters 45-53 : LuaCharacter has no field Register
source/PlayState.hx:5938: characters 22-30 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:5938: characters 37-45 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:5991: characters 19-27 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:5991: characters 34-42 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:6106: characters 21-29 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:6106: characters 36-44 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:5373: characters 22-30 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:5373: characters 37-45 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2601: characters 30-38 : openfl.media.SoundChannel has no field __source
source/PlayState.hx:2603: characters 21-29 : openfl.media.SoundChannel has no field __source
source/LuaClass.hx:182: characters 3-10 : LuaClass does not have a constructor
source/LuaClass.hx:183: characters 3-12 : Unknown identifier : className
source/LuaClass.hx:195: characters 13-27 : Unknown identifier : SetNumProperty
source/PlayState.hx:2737: characters 30-38 : openfl.media.SoundChannel has no field __source
source/PlayState.hx:2739: characters 21-29 : openfl.media.SoundChannel has no field __source
source/ResultsScreen.hx:51: characters 19-27 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:4659: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:4659: characters 35-43 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/FlxStrip.hx:60: characters 107-121 : Too many arguments
source/ResultsScreen.hx:72: characters 16-24 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/input/FlxPointer.hx:88: characters 64-75 : Null<flixel.FlxCamera> has no field viewMarginX
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/input/FlxPointer.hx:89: characters 64-75 : Null<flixel.FlxCamera> has no field viewMarginY
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/util/FlxSpriteUtil.hx:179: characters 54-68 : Null<flixel.FlxCamera> has no field viewMarginLeft
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/util/FlxSpriteUtil.hx:180: characters 22-31 : Null<flixel.FlxCamera> has no field viewRight (Suggestion: viewHeight)
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/util/FlxSpriteUtil.hx:181: characters 59-74 : Null<flixel.FlxCamera> has no field viewMarginRight
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/util/FlxSpriteUtil.hx:182: characters 22-30 : Null<flixel.FlxCamera> has no field viewLeft
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/util/FlxSpriteUtil.hx:184: characters 53-66 : Null<flixel.FlxCamera> has no field viewMarginTop
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/util/FlxSpriteUtil.hx:185: characters 22-32 : Null<flixel.FlxCamera> has no field viewBottom
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/util/FlxSpriteUtil.hx:186: characters 57-73 : Null<flixel.FlxCamera> has no field viewMarginBottom
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/util/FlxSpriteUtil.hx:187: characters 22-29 : Null<flixel.FlxCamera> has no field viewTop
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/util/FlxSpriteUtil.hx:215: characters 53-67 : Null<flixel.FlxCamera> has no field viewMarginLeft
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/util/FlxSpriteUtil.hx:216: characters 22-30 : Null<flixel.FlxCamera> has no field viewLeft
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/util/FlxSpriteUtil.hx:217: characters 60-75 : Null<flixel.FlxCamera> has no field viewMarginRight
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/util/FlxSpriteUtil.hx:218: characters 22-31 : Null<flixel.FlxCamera> has no field viewRight (Suggestion: viewHeight)
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/util/FlxSpriteUtil.hx:220: characters 50-63 : Null<flixel.FlxCamera> has no field viewMarginTop
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/util/FlxSpriteUtil.hx:221: characters 22-29 : Null<flixel.FlxCamera> has no field viewTop
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/util/FlxSpriteUtil.hx:222: characters 60-76 : Null<flixel.FlxCamera> has no field viewMarginBottom
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/util/FlxSpriteUtil.hx:223: characters 22-32 : Null<flixel.FlxCamera> has no field viewBottom

Im on windows x86/windows 11 and if anyone knows how to fix this it would be appreciated! (version 1.4.2)

**Comment by BoloVEVO** [comment]
1. 1.4.2 uses an old version of haxeflixel, try using flixel 4.11
2. You are using an incorrect version of extension-webm, check the build guide
3. You have not installed the lua libraries, check the build guide.

**Comment by KittenfanVR** [comment]
what about the flixel addons version??

**Comment by KittenfanVR** [comment]
i installed flixel addons 2.11.0 and it fixed everything i previously had issues with but now i have this error
source/ModCore.hx:38: lines 38-65 : { parseRules : polymod.format.ParseRules, modRoot : String, ignoredFiles : Array<String>, frameworkParams : polymod.FrameworkParams, framework : po... has extra field apiVersion
source/ModCore.hx:38: lines 38-65 : ... For function argument 'params'
source/ModCore.hx:69: characters 15-28 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
source/ModCore.hx:96: characters 34-47 : String should be Null<polymod.ScanParams>
source/ModCore.hx:96: characters 34-47 : ... String has no field apiVersionRule
source/ModCore.hx:96: characters 34-47 : ... For optional function argument 'scanParams'
source/ModCore.hx:98: characters 27-38 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
source/ChartingState.hx:1950: characters 33-41 : flash.media.SoundChannel has no field __source
source/ChartingState.hx:1962: characters 25-33 : flash.media.SoundChannel has no field __source
source/FreeplayState.hx:576: characters 31-39 : flash.media.SoundChannel has no field __source
source/PlayState.hx:4944: characters 14-29 : Static access to instance field SKIP_STEP_LIMIT is not allowed
source/PlayState.hx:2601: characters 30-38 : flash.media.SoundChannel has no field __source
source/PlayState.hx:2603: characters 21-29 : flash.media.SoundChannel has no field __source
source/PlayState.hx:2737: characters 30-38 : flash.media.SoundChannel has no field __source
source/PlayState.hx:2739: characters 21-29 : flash.media.SoundChannel has no field __source

should i just install v1.5 and make everything easier?

**Comment by BoloVEVO** [comment]
Oh right 1.4.2 uses an older version of openfl too but honestly1.4.2 is pretty wack by this time so you can download the latest commit version :) (kinda 1.5)
