### ISSUE TITLE
Compile issues 

### ISSUE THREAD

**Issue by ModdingGaming10** [BoloVEVO/Kade-Engine#53]
source/funkin/gameplay/GameplayCustomizeState.hx:28: characters 8-47 : Type name flixel.addons.display.MouseCallback is redefined from module flixel.addons.display.FlxExtendedMouseSprite
C:/haxelib/polymod/1,8,0/polymod/backends/LimeBackend.hx:146: characters 54-55 : Unexpected ?

**Comment by BoloVEVO** [comment]
You are using a newer version of the libraries
Try using flixel 4.11, flixel-addons 2.11 and polymod 1.7.0
Sorry for the issues I'll be updating this repo soon with a lot of changes :)

**Comment by ModdingGaming10** [comment]
i got
ource/flixel/FlxCamera.hx:1327: characters 22-23 : flixel.util.FlxAxes has no field x
source/flixel/FlxCamera.hx:1331: characters 22-23 : flixel.util.FlxAxes has no field y
source/flixel/animation/FlxAnimationController.hx:158: characters 39-47 : flixel.graphics.frames.FlxFrame has no field duration
source/flixel/FlxCamera.hx:668: characters 22-28 : flixel.graphics.tile.FlxDrawTrianglesItem has no field shader
source/flixel/FlxCamera.hx:702: characters 16-22 : flixel.graphics.tile.FlxDrawTrianglesItem has no field shader
source/flixel/FlxCamera.hx:928: characters 81-90 : Too many arguments
source/funkin/menus/FreeplayState.hx:1230: characters 20-30 : Field startOutro is declared 'override' but doesn't override any field

**Comment by BoloVEVO** [comment]
Try with latest flixel, I think you don't need an old flixel version to compile

**Comment by ModdingGaming10** [comment]
C:/haxelib/flixel/5,8,0/flixel/system/macros/FlxDefines.hx:121: characters 75-79 : Unsupported Flixel Addons version! Supported versions are 3.0.2 or newer (found 2.11.0).

**Comment by BoloVEVO** [comment]
Test with 5.x flixel versions till it lets you compile, I didn't know about this :P

**Comment by ModdingGaming10** [comment]
i got it i install haxelib install flixel-addons 3.0.2

**Comment by ModdingGaming10** [comment]
also thanks for helping me BoloVEVO

**Comment by BoloVEVO** [comment]
K ur welcome! Stay tuned for any updates 🔥
